### ISSUE TITLE
Need a new principal maintainer.

### ISSUE THREAD

**Issue by davidwhogg** [daft-dev/daft#108]
This issue relates to *all open issues*. We need a maintainer for this project, because I (@davidwhogg) am super-duper sucking. Do we have a power user who has pushed good changes who could take it over?

**Comment by dsfulf** [comment]
@davidwhogg I'd be happy to maintain the project. I'm using Daft for my master's thesis, so I have a vested interest in this.

I had to dive in pretty deep to get the auto-sizing / auto-origin to work, so I feel confident that I have a solid understanding of the project.

**Comment by davidwhogg** [comment]
Excellent! @dfm is on vacation but when he gets back we will discuss and come back to you on this thread.

**Comment by dfm** [comment]
@dsfulf: Thanks - this would be awesome! I've just created a new GitHub organization for the project and invited you both. Once you've joined the org, I can give everyone write access to the repo. Thanks again!

**Comment by dsfulf** [comment]
@davidwhogg @dfm Alright! I have a PR [#109](https://github.com/daft-dev/daft/pull/109) to update a few things. I note the website and API is a bit out of date. Also, the version on PyPi seems to be behind `master`.

Are there instructions for building the documentation? I'm familiar with Sphinx but less so with github pages.

**Comment by dfm** [comment]
@dsfulf: I love what you're doing so far!! I'll open two new issues for documenting the PyPI release process and building the docs and assign them to myself.

**Comment by davidwhogg** [comment]
This is all good; I think this issue can be closed. If you need permissions to mess with the web site, let us know.
