### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by dsfulf** [daft-dev/daft#110]
@dfm @davidwhogg I'd like to expand the unit tests and add Travis CI to confirm pull requests are compatible. Let me know if you have thoughts about this.

**Comment by davidwhogg** [comment]
Yes I agree. I don't really know how to construct unit tests, but the functional tests can involve the building of the examples...

**Comment by dsfulf** [comment]
Added config files in #113.

**Comment by dsfulf** [comment]
I believe this is working properly now!
