### ISSUE TITLE
Default fonts not working

### ISSUE THREAD

**Issue by taylorwwebb** [daft-dev/daft#128]
I'm sure this is something that's wrong on my end, but I can't figure it out: when I try to run 'The Quintessential PGM' demo, followed by a call to pgm.savefig, the resulting image uses a sans serif font, rather than the default fonts shown in the documentation (image below). Any idea what I might be doing wrong?

![prob_graph](https://user-images.githubusercontent.com/28983509/114921857-ddd62980-9ddf-11eb-8067-acf51c428cde.png)

**Comment by dfm** [comment]
Sure! The examples are all run with the following `rcParams`:

```python
import matplotlib.pyplot as mpl
mpl.rcParams["font.family"] = "serif"
mpl.rcParams["font.size"] = 12
mpl.rcParams["text.usetex"] = True
mpl.rcParams["figure.dpi"] = 150
```

Hope this helps!

**Comment by taylorwwebb** [comment]
this worked, thanks!
