### ISSUE TITLE
daft.PGM() TypeError: __init__() missing 1 required positional argument: 'shape'

### ISSUE THREAD

**Issue by arjan-hada** [daft-dev/daft#135]
The docs say the shape is an optional parameter for daft.PGM(). however, when executing "daft.PGM()" I get the following error:
TypeError: __init__() missing 1 required positional argument: 'shape'

**Comment by dfm** [comment]
Please list the specific version of daft, Python, and matplotlib. Then give an executable example with the full error traceback.

**Comment by jdmoore7** [comment]
Same problem today, it seems that `daft.pgm` expects a shape parameter but isn't offered one in a tutorial linked below
Python 3.7.12
Matplotlib 3.2.2
Daft 0.0.4

Used script from this [tutorial](https://docs.daft-pgm.org/en/latest/examples/nogray/) and the following error was returned, from the first line.

```python
pgm = daft.PGM()
>>>
TypeError                                 Traceback (most recent call last)
<ipython-input-13-06303411a32e> in <module>()
      2 
      3 # Instantiate the PGM.
----> 4 pgm = daft.PGM()
      5 
      6 # # Hierarchical parameters.

TypeError: __init__() missing 1 required positional argument: 'shape'
```
Thanks for looking into this!

**Comment by jdmoore7** [comment]
Actually, error resolves itself with Daft 0.1.2

**Comment by aysuyaman** [comment]
I am working on google colab as PyMC3 is not supported on my Mac. 
I downloaded the latest daft version with the command "!pip install daft==0.1.2" but I still get the same error. 
Do you have any suggestions?

**Comment by dfm** [comment]
What do you get when you run

```python
import daft
print(daft.__version__)
```

in your Colab notebook? The Colab environment includes v0.0.4 :/ by default, so you may need to install (I use `%pip install -U daft`) and then restart your kernel. I find that if I do that everything works.

**Comment by aysuyaman** [comment]
Thank you, but it didn't help :( 
<img width="1198" alt="Screen Shot 2022-05-03 at 19 44 55" src="https://user-images.githubusercontent.com/50742940/166500524-74503e04-2b3d-4be5-b0c1-da4a3fc62ac5.png">

**Comment by dfm** [comment]
That's cause you didn't restart your kernel!

**Comment by aysuyaman** [comment]
Touché! I'm a newbie. Thanks a lot 👍

**Comment by dfm** [comment]
Excellent - glad you got it working!!
