### ISSUE TITLE
Part of the arrows lies inside circles

### ISSUE THREAD

**Issue by senbaikang** [daft-dev/daft#140]
I tried to reproduce [this example](https://docs.daft-pgm.org/en/latest/examples/classic/). What I got is [this](https://github.com/daft-dev/daft/files/7498662/t.pdf) figure, where part of the arrows lies inside circles. Is there any way to avoid this issue so that the arrows end exactly at the circles? Thank you in advance.

My testing environment:
python=3.9.7
matplotlib=3.4.3
daft=0.1.2

**Comment by dfm** [comment]
I thought we had fixed that, but I definitely reproduce your issue too! I'm not sure that I have great suggestions, but options might include manually setting the z-order for edges and nodes? I'll take a look and let us know here if you come up with anything.

**Comment by dfm** [comment]
As a temporary solution, you can pass `plot_params=dict(fc="w")` to `add_node` for the nodes that aren't `observed` or `fixed`. Perhaps this should be the default anyways!

**Comment by senbaikang** [comment]
Fantastic! This definitely solves my issue. Thank you so much for this handy project :-)

> As a temporary solution, you can pass `plot_params=dict(fc="w")` to `add_node` for the nodes that aren't `observed` or `fixed`. Perhaps this should be the default anyways!
