### ISSUE TITLE
add documentation about include files

### ISSUE THREAD

**Issue by davidwhogg** [daft-dev/daft#4]
We should show what to do if a user wants to import daft _and_ some set of latex macros

**Comment by dsfulf** [comment]
[`thicklines.py`](https://github.com/daft-dev/daft/blob/master/examples/thicklines.py) uses the tex preamble.

Is this really an issue for `daft` or an issue for `matplotlib`?

**Comment by davidwhogg** [comment]
It is a matplotlib issue for sure. But it is useful because often for a paper we define a set of macros for all our quantities (like \data, \parameters, \noisevariance or whatever) and we want those macros to be used directly by Daft, so it integrates into the paper properly. But feel free to close since it is certainly not Daft's problem.
