### ISSUE TITLE
notify pundits

### ISSUE THREAD

**Issue by davidwhogg** [daft-dev/daft#40]
Koller, Sontag, Fergus, LeCun, Murray, Marshall, Harmeling, Hirsch, etc.  And people at CMML.  And the CMMLU.  And etc.

**Comment by dsfulf** [comment]
@dfm @davidwhogg Any reason to keep this open? I think to do so, it needs more context for the current conversation...

**Comment by dfm** [comment]
Haha - no we can definitely close it 😊
