### ISSUE TITLE
do edges ever need labels?

### ISSUE THREAD

**Issue by davidwhogg** [daft-dev/daft#41]
If so, `Edge()` has to become an object.  I think we should do this only if asked.

**Comment by timothyb0912** [comment]
I think having edge labels would be useful. For instance, if one wanted to use daft to represent decision trees (with binary or multiway splits), then having edge labels would allow separation of the condition corresponding to an edge from the variable used to do the splitting (which would be used to label the node). See for example: https://image.slidesharecdn.com/decisiontree-151015165353-lva1-app6892/95/classification-using-decision-tree-12-638.jpg?cb=1444928106

**Comment by dsfulf** [comment]
Edges have labels... could use some enhancement, e.g. help with positioning, adding solid background if desired to cover edges, etc.

**Comment by dsfulf** [comment]
See #67.
