### ISSUE TITLE
`text` method

### ISSUE THREAD

**Issue by davidwhogg** [daft-dev/daft#60]
I often want to _just write text_ on my PGM.  We should provide a general `text` method or `label` method that permits this.  Am hacking `Plate` right now (and feeling dirty).

**Comment by dsfulf** [comment]
I think this can be implemented as a subclass of `pgm.Plate()`.

**Comment by dsfulf** [comment]
Added `PGM.Text` class and `PGM.add_text` method to #109. Example use in `deconvolution.py`.
