### ISSUE TITLE
Where do the numbers come from?

### ISSUE THREAD

**Issue by eli-b** [daft-dev/daft#68]
All of the examples show hard-coded numbers for shape, origin, grid_units, node_units and, of course, x,y positions. Some of them seem non-trivial, too.

To the programmer reading the code this isn't very communicative. Usually nodes are "directly below" or "directly to the side" of another node. I don't believe just using the same x or y value for this is a good solution - if I later want to move the row elsewhere I'll have to correct the row number on every node on it.

I understand we're dealing with visual display here and some hand-tweaking is probably unavoidable, but is there a good convention to deal with this issue?

**Comment by dsfulf** [comment]
Auto sizing and scaling obviates some of this, but fundamentally the graph is laid out onto a grid. The grid can be computed with helper functions, or stored to variables. "correcting the row number of every node" is really a matter of storing the common row number into a variable.

For something more automatic see [daft-builder](https://github.com/macks22/daft-builder).

**Comment by eli-b** [comment]
daft-builder looks neat, thanks.

Could you elaborate on auto sizing and scaling too, please?

**Comment by dsfulf** [comment]
Please take a look at the examples in #109. Manually setting the size and offset upon initiation of `daft.PGM()` is no longer required.
