### ISSUE TITLE
Inner and shaded nodes in same graph

### ISSUE THREAD

**Issue by lindeloev** [daft-dev/daft#94]
Lee & Wagenmakers (2014) propose to add inner circles for deterministic nodes and shaded for observed nodes. However, I have to choose in `daft.PGM(observed_style='shaded')`.

For now, my workaround is to add another "empty" scaled down node, but the spaces between the two are not equal for ellipses for which the scaling changes more in one direction than another. So it is not satisfactory.

    pgm.add_node(daft.Node('det', '$node$', 0, 0, aspect=2))  # Deterministic
    pgm.add_node(daft.Node('none', '', 0, 0, scale=0.85, aspect=2))  # Inner ellipse on deterministic
    pgm.add_node(daft.Node('obs', '$obs$', 1, 1, observed=True))  # Shaded observed

**Comment by davidwhogg** [comment]
This is a good idea; we should have the nodes "inherit" observed_style but permit it to be over-ridden.

Our development is slow these days, but if you want to hack, it is an open-source project, and we accept pull requests!

**Comment by lindeloev** [comment]
I'd rather there was a `deterministic_style` in `daft.PGM` too and an option to set `deterministic = True` in `daft.Node`

I have too much on my plate these days, unfortunately. But now the idea is presented :-)

**Comment by davidwhogg** [comment]
There is a “fixed” style , so this already exists. We just need to give it more options.

**Comment by dsfulf** [comment]
Added this as an option to #106.

**Comment by dsfulf** [comment]
This should integrate with #69, in a future version enhance to allow multiple node types set via a `dict` of some kinds rather than several boolean arguments.
