### ISSUE TITLE
Edge penetrating node on example MRF

### ISSUE THREAD

**Issue by ptbrowne** [daft-dev/daft#95]
Some edges are penetrating the nodes in the example : 

![image](https://user-images.githubusercontent.com/465582/33808144-ad8e145c-dde1-11e7-9c36-885520d4a599.png)

http://daft-pgm.org/examples/mrf/

**Comment by davidwhogg** [comment]
Yes! We consider this a matplotlib bug, but I'm stumped.

**Comment by dsfulf** [comment]
This seems better in current version.

![mrf](https://user-images.githubusercontent.com/8421927/64505231-c399a880-d298-11e9-9e39-4dea6055dcd8.png)

**Comment by ptbrowne** [comment]
Thanks for the follow up !
