### ISSUE TITLE
rectangle nodes not working

### ISSUE THREAD

**Issue by murphyk** [daft-dev/daft#97]
extension from @parleur to make nodes be rectangles instead of ellipses is not working correctly.
The text is not centered inside rectangle but appears on top right corner.
And edges are not aligned with edges of box.

Simple code to reproduce bug (and its result) shown below.

import os
import imp
import daft
pgm = daft.PGM([8, 9], origin=[0, 0], observed_style="inner")
x = 2
pgm.add_node(daft.Node("se", r"se", x-1, 3))
pgm.add_node(daft.Node("ge", r"ge", x+1, 3))
#pgm.add_node(daft.Node("Ot1", r"$O_{t-1}$", x, 4, shape="ellipse"))
pgm.add_node(daft.Node("O", r"$O_{t-1}$", x, 4, shape="rectangle"))
pgm.add_edge("se", "O")
pgm.add_edge("O", "ge")
pgm.render()
folder = "/Users/kpmurphy/github/pyprobml/figures"
fname = "rectangle-bug"
pgm.figure.savefig(os.path.join(folder, "{}.png".format(fname)))

![rectangle-bug](https://user-images.githubusercontent.com/4632336/37444456-e4107f2e-27ce-11e8-8572-e27f77e99a6b.png)

**Comment by davidwhogg** [comment]
Thanks for the minimal example. I wonder if this is backend stuff or a simple bug?

**Comment by parleur** [comment]
I'll having a look at it these days, see what I can do and report. ty for the bug report.

**Comment by parleur** [comment]
Weirdly, this code works:
```
pgm.add_node(daft.Node("O", r"$O_{t-1}$", x, 4., shape="rectangle"))
```
But this one not:
```
pgm.add_node(daft.Node("O", r"$O_{t-1}$", x, 4, shape="rectangle"))
```
And yes that's in python3, although, back to original commit, I think I was using 2.7 for this PL. 
Close to find the bug.

**Comment by parleur** [comment]
Should do the job.

**Comment by murphyk** [comment]
great, thanks

**Comment by davidwhogg** [comment]
Yay!

**Comment by dsfulf** [comment]
Closed due to completion.
